jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Check Snippets
      run: python scripts/checksnippets.py
    - continue-on-error: true
      name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install
        "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Build with Gradle (Pull Request)
      run: ./build_pull_request.sh
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Build with Gradle (Push)
      run: ./gradlew clean ktlint build
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
